In [4]:
import numpy as np
from itertools import combinations, product, permutations
import warnings
import time
from idQ import is_parallel, is_strictly_less_than, is_less_equal_than, generate_binary_vectors, generate_permutations, get_D_l, height_of_Q, distances2U, preserve_partial_order
from idQ import generate_DAG, generate_hasse_diagram, check_for_identity, Any_two_columns_contain_I, topo_order, incomplete_global_identifiability
import random
from expr_function import random_generate_Q, generate_canonical_matrices, binary_matrix_to_string, sort_lexicographically, random_generate_Q, prop_check, sort_binary_matrix
import sys
import itertools
import cProfile
import random
from idQ import T_mat, get_D_l, get_D

In [11]:
import numpy as np

def calculate_R_matrix(Q_matrix):
    """
    Calculate the R-matrix for a given Q-matrix.

    Args:
    Q_matrix (numpy.ndarray): A binary matrix (Q-matrix) of dimensions J x K.

    Returns:
    numpy.ndarray: The R-matrix of dimensions J x 2^K.
    """
    J, K = Q_matrix.shape  # J items and K attributes
    num_attribute_profiles = 2 ** K  # Total number of possible attribute profiles
    
    # Generate all possible attribute profiles (binary representations of numbers 0 to 2^K - 1)
    attribute_profiles = np.array([list(np.binary_repr(i, width=K)) for i in range(num_attribute_profiles)], dtype=int)
    
    # Initialize the R-matrix
    R_matrix = np.zeros((J, num_attribute_profiles), dtype=int)

    # Compute the R-matrix
    for j in range(J):
        for a in range(num_attribute_profiles):
            # Compute the XOR product and mod 2 for each entry
            R_matrix[j, a] = np.bitwise_and(Q_matrix[j, :], attribute_profiles[a, :]).sum() % 2

            
    # Get unique columns of R_matrix to form R^mcr matrix
    R_mcr_matrix, indices = np.unique(R_matrix, axis=1, return_index=True)

    # Sort the matrix based on the indices to maintain the original order
    R_mcr_matrix = R_mcr_matrix[:,np.argsort(indices)]
    
    return R_matrix, R_mcr_matrix

# Example Q-matrix
Q_matrix_example = np.array([[1, 1, 0], [1, 0, 1], [0, 1, 1]])

# Compute R-matrix
_, R_mcr_matrix_example = calculate_R_matrix(Q_matrix_example)
R_mcr_matrix_example



array([[0, 0, 1, 1],
       [0, 1, 0, 1],
       [0, 1, 1, 0]])

In [12]:
for Q in generate_canonical_matrices(3, 3):
    R, R_mcr = calculate_R_matrix(Q)
    print(Q)
    print(R_mcr)

[[0 0 1]
 [0 1 0]
 [0 1 1]]
[[0 1 0 1]
 [0 0 1 1]
 [0 1 1 0]]
[[0 0 1]
 [0 1 0]
 [1 0 0]]
[[0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 1]]
[[0 0 1]
 [0 1 0]
 [1 0 1]]
[[0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1]
 [0 1 0 1 1 0 1 0]]
[[0 0 1]
 [0 1 0]
 [1 1 1]]
[[0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1]
 [0 1 1 0 1 0 0 1]]
[[0 0 1]
 [0 1 1]
 [1 0 1]]
[[0 1 0 1 0 1 0 1]
 [0 1 1 0 0 1 1 0]
 [0 1 0 1 1 0 1 0]]
[[0 0 1]
 [0 1 1]
 [1 1 0]]
[[0 1 0 1 0 1 0 1]
 [0 1 1 0 0 1 1 0]
 [0 0 1 1 1 1 0 0]]
[[0 0 1]
 [0 1 1]
 [1 1 1]]
[[0 1 0 1 0 1 0 1]
 [0 1 1 0 0 1 1 0]
 [0 1 1 0 1 0 0 1]]
[[0 0 1]
 [1 1 0]
 [1 1 1]]
[[0 1 0 1]
 [0 0 1 1]
 [0 1 1 0]]
[[0 1 1]
 [1 0 1]
 [1 1 0]]
[[0 1 1 0]
 [0 1 0 1]
 [0 0 1 1]]
[[0 1 1]
 [1 0 1]
 [1 1 1]]
[[0 1 1 0 0 1 1 0]
 [0 1 0 1 1 0 1 0]
 [0 1 1 0 1 0 0 1]]
