In [4]:
import numpy as np
from itertools import combinations, product, permutations
import warnings
import time
from idQ import is_parallel, is_strictly_less_than, is_less_equal_than, generate_binary_vectors, generate_permutations, get_D_l, height_of_Q, distances2U, preserve_partial_order
from idQ import generate_DAG, generate_hasse_diagram, check_for_identity, Any_two_columns_contain_I, topo_order, incomplete_global_identifiability
import random
from expr_function import random_generate_Q, generate_canonical_matrices, binary_matrix_to_string, sort_lexicographically, random_generate_Q, prop_check, sort_binary_matrix
import sys
import itertools
import cProfile
import random
from idQ import T_mat, get_D_l, get_D

In [1]:
import itertools
import numpy as np

# Define Q^(b) as a numpy array
Qb = np.array([
    [0, 1, 0],
    [0, 0, 1],
    [1, 1, 0],
    [1, 0, 1]
])

# Get all permutations of column indices for a 3-column matrix
cols = list(range(Qb.shape[1]))
permutations = list(itertools.permutations(cols))

# Use a set to store distinct row sets (represented as frozensets of tuples)
distinct_row_sets = set()

for perm in permutations:
    # Permute the columns
    Qb_perm = Qb[:, perm]
    # Convert each row into a tuple and create a frozenset (order-independent)
    row_set = frozenset(tuple(row) for row in Qb_perm)
    distinct_row_sets.add(row_set)

# Display the distinct row sets and their count
print("Number of distinct row sets:", len(distinct_row_sets))
for idx, row_set in enumerate(distinct_row_sets, 1):
    print(f"Row set {idx}: {sorted(list(row_set))}")


Number of distinct row sets: 3
Row set 1: [(0, 1, 0), (0, 1, 1), (1, 0, 0), (1, 0, 1)]
Row set 2: [(0, 0, 1), (0, 1, 1), (1, 0, 0), (1, 1, 0)]
Row set 3: [(0, 0, 1), (0, 1, 0), (1, 0, 1), (1, 1, 0)]


In [ ]:
T3 = {(0,1,0), (0,0,1), (1,1,0), (1,0,1)}

In [12]:
for Q in generate_canonical_matrices(3, 3):
    R, R_mcr = calculate_R_matrix(Q)
    print(Q)
    print(R_mcr)

[[0 0 1]
 [0 1 0]
 [0 1 1]]
[[0 1 0 1]
 [0 0 1 1]
 [0 1 1 0]]
[[0 0 1]
 [0 1 0]
 [1 0 0]]
[[0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 1]]
[[0 0 1]
 [0 1 0]
 [1 0 1]]
[[0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1]
 [0 1 0 1 1 0 1 0]]
[[0 0 1]
 [0 1 0]
 [1 1 1]]
[[0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1]
 [0 1 1 0 1 0 0 1]]
[[0 0 1]
 [0 1 1]
 [1 0 1]]
[[0 1 0 1 0 1 0 1]
 [0 1 1 0 0 1 1 0]
 [0 1 0 1 1 0 1 0]]
[[0 0 1]
 [0 1 1]
 [1 1 0]]
[[0 1 0 1 0 1 0 1]
 [0 1 1 0 0 1 1 0]
 [0 0 1 1 1 1 0 0]]
[[0 0 1]
 [0 1 1]
 [1 1 1]]
[[0 1 0 1 0 1 0 1]
 [0 1 1 0 0 1 1 0]
 [0 1 1 0 1 0 0 1]]
[[0 0 1]
 [1 1 0]
 [1 1 1]]
[[0 1 0 1]
 [0 0 1 1]
 [0 1 1 0]]
[[0 1 1]
 [1 0 1]
 [1 1 0]]
[[0 1 1 0]
 [0 1 0 1]
 [0 0 1 1]]
[[0 1 1]
 [1 0 1]
 [1 1 1]]
[[0 1 1 0 0 1 1 0]
 [0 1 0 1 1 0 1 0]
 [0 1 1 0 1 0 0 1]]
